{
    'name': 'Recouvrement, litiges et contentieux',
    'version': '19.0.1.0.0',
    'summary': 'Gestion des factures, recouvrements, actions et procédures',
    'description': 'Module de gestion des recouvrements, litiges et contentieux pour CID Développement.',
    'category': 'Accounting',
    'sequence': 10,
    'author': 'CID Développement',
    'license': 'OPL-1',
    'depends': ['base', 'account', 'hr', 'mail'],
    'data': [
        'security/recouvrement_security.xml',
        'security/ir.model.access.csv',
        'data/recouvrement_data.xml',
        'views/res_partner_views.xml',
        'views/recouvrement_relances.xml',
        'views/recouvrement_menu.xml',
        'views/recouvrement_views.xml',
        'views/recouvrement_import_wizard.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'recouvrement_contentieux/static/src/scss/recouvrement_dashboard.scss',
            'recouvrement_contentieux/static/src/js/recouvrement_dashboard.js',
            'recouvrement_contentieux/static/src/xml/recouvrement_dashboard.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
